### ISSUE TITLE
incr写事务窄传输时遇到的，w_buffer没有偏移的问题

### ISSUE THREAD

**Issue by GreensCH** [cyyself/soc-simulator#1]
#### 问题背景：

我在使用soc_simulator实现**incr**类型的写事务过程中 (burst_len=0, burst_size=3, 数据总线宽度为64，地址总线宽度为32)遇到了一个问题

当窄传输时（一个传输示例如下），soc_simulator遇到了数据写入（axi4_mem.do_write处）为0的问题

![image-20220721153645911](https://raw.githubusercontent.com/GreensCH/blog-drawbed/main/common/image-20220721153645911.png)

仔细阅读源码后，发现程序axi4_slave.hpp:216处，作为存放wdata的w_buffer，传入do_wirte时所添加的偏移地址，in_data_pos**始终为0**，造成了无法与`addr_base+addr`添加偏移地址的写地址所对应，因此写入了不存在的0

![image-20220721151449057](https://raw.githubusercontent.com/GreensCH/blog-drawbed/main/common/image-20220721151449057.png)

![image-20220721151432862](https://raw.githubusercontent.com/GreensCH/blog-drawbed/main/common/image-20220721151432862.png)

#### 个人解决办法：

修改axi4_slave.hpp:216的do_write的`w_buffer + in_data_pos`为`w_buffer + addr`，即与前写地址偏移时的偏移量相同。完整216行代码如下：

```c++
w_resp = static_cast<axi_resp>(static_cast<int>(w_resp) | static_cast<int>(do_write(addr_base+addr,len,w_buffer+addr)));
```

修改过后的代码通过了全部cpu_test

#### **最终问题：**

1. 假设写事务过程没有问题，我对soc_simlator修改是否有危害，这种修改是否破坏了模型的正确性
2. 如果修改有危害，可否给出一种可行的修改方案
3. 由于我是在测试我的rtl代码实现的axi代码是否有误，因此修改过后的soc_simlator我无法确认是否满足要求，想问一下下面这个写事务是否正确

> 这里叙述一个我axi的写操作，当我需要往0x800013C地址写入一个word数据时，一个写事务的主要信息：
>
> + aw_burst = INCR
> + aw_len = 0
> + aw_size  = 3
> + aw_addr = 0x80000138
> + w_mask = 0b11110000
> + w_data = 0hxxxx_xxxx_0000_0000

**Comment by cyyself** [comment]
感谢指出，已在commit e19b18e4d72a045aebc5de3eaf997403d92eab43 中修正
