### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Dorbmon** [cyyself/soc-simulator#2]
In axi4.hpp, it is supposed to include <set> or you will get error:
`axi4.hpp:66:14: error: ‘set’ is not a member of ‘std’
   66 |         std::set <void*> s;`

**Comment by cyyself** [comment]
fixed at commit #[d923c73](https://github.com/cyyself/soc-simulator/commit/d923c73bce3b5006a9606201c2c07aa4b854e36a)
