### ISSUE TITLE
Request to Add a LICENSE File

### ISSUE THREAD

**Issue by pointerliu** [cyyself/soc-simulator#4]
Hello cyyself,

I hope you're doing well. I would like to request the addition of a LICENSE file to the repository. As we may want to fork and further develop this project, having a clear license will clarify the terms under which your work can be used and shared by others.

Thank you for considering this request! I appreciate your work on this project.

**Comment by cyyself** [comment]
OK. https://github.com/cyyself/soc-simulator/commit/9ba6c5729ecdf4088ad576cafd90578d8a815823
